prefix = "."
stop-words = "stopwords.txt"
dataset = "dataset"
corpus = "line.toml"
index = "index"

[[analyzers]]
method = "ngram-word"
ngram = 1
    [[analyzers.filter]]
    type = "icu-tokenizer"

    [[analyzers.filter]]
    type = "lowercase"

    [[analyzers.filter]]
    type = "porter2-filter"

    [[analyzers.filter]]
    type = "length"
    min = 3
    max = 35